import React, { useEffect, useState } from "react";
import { ExternalLink, Plus, FileText, ShieldAlert } from "lucide-react";
import { REPORTS } from "../data/reports.js";
import { VENUES } from "../data/venues.js";
import { api, validSource } from "../lib/cloud.js";
export default function Reports({ cloudKey, openCloud }) {
  const [saved, setSaved] = useState([]), [water, setWater] = useState("all"), [showForm, setShow] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [form, setForm] = useState({ venueId: "thornwood", eventDate: "", title: "", text: "", url: "" });
  useEffect(() => { let active = true; if (cloudKey) api("/reports", { key: cloudKey }).then(d => { if (active) setSaved(d.items); }).catch(e => { if (active) setError(e.message); }); else setSaved([]); return () => { active = false; }; }, [cloudKey]);
  const reports = [...saved, ...REPORTS].filter(r => water === "all" || r.venueId === water);
  async function save(e) { e.preventDefault(); setBusy(true); setError(""); try { const r = await api("/reports", { key: cloudKey, body: form }); setSaved(r.items); setShow(false); setForm({ ...form, title: "", text: "", url: "" }); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  return <div>
    <div className="page-heading"><div><p className="eyebrow">NOTICES & FIELD INTELLIGENCE</p><h1>News from the fisheries.</h1><p>Traceable reports, stocking information and the details worth checking before you travel.</p></div><button className="button primary" onClick={() => cloudKey ? setShow(!showForm) : openCloud()}><Plus size={17} /> Save a report</button></div>
    <div className="notice-strip"><FileText size={22} /><div><strong>No invented stocking updates.</strong><p>There is no connected universal fishery feed here. Operator notices are curated and date-stamped; your saved reports are private and not independently verified. A seasonal target is never shown as a recent stocking.</p></div></div>
    {error && <p role="alert" className="inline-error">{error}</p>}
    {showForm && <form className="panel report-form" onSubmit={save}><div className="section-heading"><h2>Save the original report</h2><button type="button" className="text-button" onClick={() => setShow(false)}>Cancel</button></div><div className="form-grid"><label className="field-label">Water<select value={form.venueId} onChange={e => setForm({ ...form, venueId: e.target.value })}>{VENUES.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label className="field-label">Report / event date<input type="date" required max={new Date().toISOString().slice(0, 10)} value={form.eventDate} onChange={e => setForm({ ...form, eventDate: e.target.value })} /></label><label className="field-label">Headline<input required maxLength={160} value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></label><label className="field-label">Original source URL<input type="url" required placeholder="https://fishery.example/report" value={form.url} onChange={e => setForm({ ...form, url: e.target.value })} /></label></div><label className="field-label">Your summary<textarea maxLength={1200} value={form.text} onChange={e => setForm({ ...form, text: e.target.value })} /></label><button className="button primary" disabled={busy}>{busy ? "Saving…" : "Save to private logbook"}</button></form>}
    <div className="section-heading"><h2>Report board</h2><label><span className="sr-only">Filter reports by water</span><select aria-label="Filter reports by water" value={water} onChange={e => setWater(e.target.value)}><option value="all">All waters</option>{VENUES.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label></div>
    <div className="report-board">{reports.map(r => <article className="panel report-card" key={r.id}><div className="section-heading"><span className={`data-pill ${r.type === "closure" ? "warning" : ""}`}>{r.type}</span><span className="small muted">Checked {r.checkedAt}</span></div><p className="eyebrow">{VENUES.find(v => v.id === r.venueId)?.name}</p><h2>{r.title}</h2>{r.eventDate && <p className="small">Reported date: {r.eventDate}</p>}<p>{r.text}</p><a className="text-button" href={validSource(r.url) ? r.url : undefined} target="_blank" rel="noreferrer">{r.source} <ExternalLink size={16} /></a></article>)}</div>
    {!reports.length && <section className="panel empty-state"><FileText size={28} /><h2>No dated report saved for this water.</h2><p>This means “unconfirmed”, not “not stocked”. Open the fishery's site or save a report with its original source.</p></section>}
    <section className="panel directory"><h2>Check directly with the fishery</h2><p className="muted">These are the existing venue-directory links, not verified live report feeds. Contact the operator to confirm opening, stocking and restrictions.</p><div className="directory-grid">{VENUES.filter(v => water === "all" || v.id === water).map(v => <a key={v.id} href={v.website} target="_blank" rel="noreferrer">{v.name}<ExternalLink size={14} /></a>)}</div></section>
  </div>;
}
